### ISSUE TITLE
Appcrash #enable-chrome-duplex

### ISSUE THREAD

**Issue by gdgsdg123** [kiwibrowser/android#20]
201810222057.apk

chrome://flags/#enable-chrome-duplex
Enabled

Appcrash on start-up.

**Comment by gdgsdg123** [comment]
Process: com.kiwibrowser.browser
Flags: 0xc83e44
Package: com.kiwibrowser.browser v43 (Watermelon)
Build: Xiaomi/full_lte26007/lte26007:4.4.4/KTU84Q/6.1.28:user/release-keys

android.view.InflateException: Binary XML file line #53: Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:623)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
	at android.view.ViewStub.inflate(ViewStub.java:259)
	at aYA.<init>(PG:63)
	at aZp.a(PG:722)
	at org.chromium.chrome.browser.ChromeTabbedActivity.N(PG:4849)
	at auL.run(PG:311)
	at auw.run(PG:28)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5135)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:597)
	... 21 more
Caused by: java.lang.NumberFormatException: Invalid int: "res/color/dark_mode_tint.xml"
	at java.lang.Integer.invalidInt(Integer.java:137)
	at java.lang.Integer.parse(Integer.java:374)
	at java.lang.Integer.parseInt(Integer.java:365)
	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:128)
	at android.content.res.TypedArray.getInt(TypedArray.java:255)
	at android.widget.ImageView.<init>(ImageView.java:155)
	at android.widget.ImageButton.<init>(ImageButton.java:87)
	at android.widget.ImageButton.<init>(ImageButton.java:83)
	at org.chromium.chrome.browser.widget.TintedImageButton.<init>(PG:28)
	... 24 more

**Comment by gdgsdg123** [comment]
And something irrelevant but may help:
[data_app_crash@1542856159638.txt](https://github.com/kiwibrowser/android/files/2607303/data_app_crash.1542856159638.txt)

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
